spring:
  datasource:
    password: 12345
    url: jdbc:postgresql://localhost:5433/bootCampDb
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
            
            

jwt:
  expiration: 160000
  secret: mySecret
